// <auto-generated />
using System;
using AutoTrainer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoTrainer.Api.Data.Migrations.Animal
{
    [DbContext(typeof(AnimalDbContext))]
    [Migration("20260914221658_AddIntertrialResultTables")]
    partial class AddIntertrialResultTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.AnimalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DcsSendX")
                        .HasColumnType("REAL");

                    b.Property<double>("DcsSendY")
                        .HasColumnType("REAL");

                    b.Property<double>("DcsSendZ")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetYLimit")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnimalHistory", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.BatchAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnalysisTrialCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailedTrialCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("BatchAnalysis", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.HandReachEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DelaySincePresented")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntertrialResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntertrialResultId");

                    b.ToTable("HandReachEvent", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.IntertrialResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RhMaxVpList")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulReaches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReaches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrialId")
                        .IsUnique();

                    b.ToTable("IntertrialResult", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.OtherReachEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DelaySincePresented")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntertrialResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntertrialResultId");

                    b.ToTable("OtherReachEvent", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.RawReachEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DelaySincePresented")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntertrialResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntertrialResultId");

                    b.HasIndex("TrialId");

                    b.ToTable("RawReachEvent", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.ReachStatusDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Day")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PelletsConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PelletsPresented")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reaches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulReaches")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReachStatusDay", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.ReachStatusTotal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PelletsConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PelletsPresented")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reaches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulReaches")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReachStatusTotal", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnalysisTrialCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaptureTrialCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailedTrialCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAnalysisDeferred")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.Trial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AnimalSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BatchAnalysisId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CaptureEndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Identifier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IntertrialDetectionBeginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IntertrialDetectionEndAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntertrialDetectionError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IntertrialDetectionSaveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntertrialDetectionSaveError")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntertrialDetectionSaveLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntertrialPelletShift")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IntertrialSegmentationBeginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IntertrialSegmentationEndAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntertrialSegmentationError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IntertrialSegmentationSaveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntertrialSegmentationSaveError")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntertrialSegmentationSaveLocation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PelletPresentedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PelletSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RightHandSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchAnalysisId");

                    b.HasIndex("SessionId", "Identifier")
                        .IsUnique();

                    b.ToTable("Trial", (string)null);
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.BatchAnalysis", b =>
                {
                    b.HasOne("AutoTrainer.Api.Data.Entities.Session", "Session")
                        .WithMany("BatchAnalyses")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.HandReachEvent", b =>
                {
                    b.HasOne("AutoTrainer.Api.Data.Entities.IntertrialResult", "IntertrialResult")
                        .WithMany("HandReachEvents")
                        .HasForeignKey("IntertrialResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntertrialResult");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.IntertrialResult", b =>
                {
                    b.HasOne("AutoTrainer.Api.Data.Entities.Trial", "Trial")
                        .WithOne("IntertrialResult")
                        .HasForeignKey("AutoTrainer.Api.Data.Entities.IntertrialResult", "TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.OtherReachEvent", b =>
                {
                    b.HasOne("AutoTrainer.Api.Data.Entities.IntertrialResult", "IntertrialResult")
                        .WithMany("OtherReachEvents")
                        .HasForeignKey("IntertrialResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntertrialResult");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.RawReachEvent", b =>
                {
                    b.HasOne("AutoTrainer.Api.Data.Entities.IntertrialResult", "IntertrialResult")
                        .WithMany("RawReachEvents")
                        .HasForeignKey("IntertrialResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTrainer.Api.Data.Entities.Trial", "Trial")
                        .WithMany("RawReachEvents")
                        .HasForeignKey("TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntertrialResult");

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.Trial", b =>
                {
                    b.HasOne("AutoTrainer.Api.Data.Entities.BatchAnalysis", "BatchAnalysis")
                        .WithMany("Trials")
                        .HasForeignKey("BatchAnalysisId");

                    b.HasOne("AutoTrainer.Api.Data.Entities.Session", "Session")
                        .WithMany("Trials")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchAnalysis");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.BatchAnalysis", b =>
                {
                    b.Navigation("Trials");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.IntertrialResult", b =>
                {
                    b.Navigation("HandReachEvents");

                    b.Navigation("OtherReachEvents");

                    b.Navigation("RawReachEvents");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.Session", b =>
                {
                    b.Navigation("BatchAnalyses");

                    b.Navigation("Trials");
                });

            modelBuilder.Entity("AutoTrainer.Api.Data.Entities.Trial", b =>
                {
                    b.Navigation("IntertrialResult");

                    b.Navigation("RawReachEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
