# https://taskfile.dev

version: '3'

vars:
  REPOSITORY: ghcr.io
  IMAGE:
    sh: jq -r .name "docker-version.json"
  REPO_IMAGE: "{{.REPOSITORY}}/{{.IMAGE}}"
  PLATFORMS: linux/amd64,linux/arm64/v8
  VERSION:
    sh: jq -r .version "docker-version.json"
  MAJOR:
    sh: bash -c 'string={{.VERSION}} && arr=(${string//"."/ }) && echo ${arr[0]}'
  MINOR:
    sh: bash -c 'string={{.VERSION}} && arr=(${string//"."/ }) && echo ${arr[1]}'
  REVISION:
    sh: bash -c 'string={{.VERSION}} && arr=(${string//"."/ }) && echo ${arr[2]}'
  IMAGE_WITH_VERSION: "{{.REPO_IMAGE}}:{{.MAJOR}}"
  IMAGE_WITH_MINOR_VERSION: "{{.IMAGE_WITH_VERSION}}.{{.MINOR}}"
  IMAGE_WITH_REVISION: "{{.IMAGE_WITH_MINOR_VERSION}}.{{.REVISION}}"
  IMAGE_LATEST: "{{.REPO_IMAGE}}:latest"

tasks:
  build:
    cmds:
      - docker build --tag {{.IMAGE_WITH_VERSION}} .
      - docker tag {{.IMAGE_WITH_VERSION}} {{.IMAGE_WITH_MINOR_VERSION}}
      - docker tag {{.IMAGE_WITH_MINOR_VERSION}} {{.IMAGE_WITH_REVISION}}
      - docker tag {{.IMAGE_WITH_REVISION}} {{.IMAGE_LATEST}}
  release:
    cmds:
      - >-
        docker buildx build --platform {{.PLATFORMS}}
        --tag {{.IMAGE_WITH_VERSION}}
        --tag {{.IMAGE_WITH_MINOR_VERSION}}
        --tag {{.IMAGE_WITH_REVISION}}
        --tag {{.IMAGE_LATEST}}
        --push .
